// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.web;

import com.test.domain.Tast;
import com.test.web.TastController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect TastController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String TastController.create(@Valid Tast tast, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, tast);
            return "tasts/create";
        }
        uiModel.asMap().clear();
        tast.persist();
        return "redirect:/tasts/" + encodeUrlPathSegment(tast.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String TastController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Tast());
        return "tasts/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String TastController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("tast", Tast.findTast(id));
        uiModel.addAttribute("itemId", id);
        return "tasts/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String TastController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("tasts", Tast.findTastEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Tast.countTasts() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("tasts", Tast.findAllTasts(sortFieldName, sortOrder));
        }
        return "tasts/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String TastController.update(@Valid Tast tast, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, tast);
            return "tasts/update";
        }
        uiModel.asMap().clear();
        tast.merge();
        return "redirect:/tasts/" + encodeUrlPathSegment(tast.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String TastController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Tast.findTast(id));
        return "tasts/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String TastController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Tast tast = Tast.findTast(id);
        tast.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/tasts";
    }
    
    void TastController.populateEditForm(Model uiModel, Tast tast) {
        uiModel.addAttribute("tast", tast);
    }
    
    String TastController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
