// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Save;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Save_Roo_Jpa_Entity {
    
    declare @type: Save: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Save.id;
    
    @Version
    @Column(name = "version")
    private Integer Save.version;
    
    public Long Save.getId() {
        return this.id;
    }
    
    public void Save.setId(Long id) {
        this.id = id;
    }
    
    public Integer Save.getVersion() {
        return this.version;
    }
    
    public void Save.setVersion(Integer version) {
        this.version = version;
    }
    
}
