// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Tast;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Tast_Roo_Configurable {
    
    declare @type: Tast: @Configurable;
    
}
