// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Tast;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Tast_Roo_Jpa_Entity {
    
    declare @type: Tast: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Tast.id;
    
    @Version
    @Column(name = "version")
    private Integer Tast.version;
    
    public Long Tast.getId() {
        return this.id;
    }
    
    public void Tast.setId(Long id) {
        this.id = id;
    }
    
    public Integer Tast.getVersion() {
        return this.version;
    }
    
    public void Tast.setVersion(Integer version) {
        this.version = version;
    }
    
}
