// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Tast;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tast_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Tast.entityManager;
    
    public static final List<String> Tast.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager Tast.entityManager() {
        EntityManager em = new Tast().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tast.countTasts() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tast o", Long.class).getSingleResult();
    }
    
    public static List<Tast> Tast.findAllTasts() {
        return entityManager().createQuery("SELECT o FROM Tast o", Tast.class).getResultList();
    }
    
    public static List<Tast> Tast.findAllTasts(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Tast o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Tast.class).getResultList();
    }
    
    public static Tast Tast.findTast(Long id) {
        if (id == null) return null;
        return entityManager().find(Tast.class, id);
    }
    
    public static List<Tast> Tast.findTastEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tast o", Tast.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Tast> Tast.findTastEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Tast o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Tast.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Tast.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tast.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tast attached = Tast.findTast(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tast.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tast.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tast Tast.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tast merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
