// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Xxx2;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Xxx2_Roo_Jpa_Entity {
    
    declare @type: Xxx2: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Xxx2.id;
    
    @Version
    @Column(name = "version")
    private Integer Xxx2.version;
    
    public Long Xxx2.getId() {
        return this.id;
    }
    
    public void Xxx2.setId(Long id) {
        this.id = id;
    }
    
    public Integer Xxx2.getVersion() {
        return this.version;
    }
    
    public void Xxx2.setVersion(Integer version) {
        this.version = version;
    }
    
}
