// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Xxx;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Xxx_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Xxx.entityManager;
    
    public static final List<String> Xxx.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager Xxx.entityManager() {
        EntityManager em = new Xxx().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Xxx.countXxxes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Xxx o", Long.class).getSingleResult();
    }
    
    public static List<Xxx> Xxx.findAllXxxes() {
        return entityManager().createQuery("SELECT o FROM Xxx o", Xxx.class).getResultList();
    }
    
    public static List<Xxx> Xxx.findAllXxxes(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Xxx o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Xxx.class).getResultList();
    }
    
    public static Xxx Xxx.findXxx(Long id) {
        if (id == null) return null;
        return entityManager().find(Xxx.class, id);
    }
    
    public static List<Xxx> Xxx.findXxxEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Xxx o", Xxx.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Xxx> Xxx.findXxxEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Xxx o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Xxx.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Xxx.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Xxx.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Xxx attached = Xxx.findXxx(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Xxx.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Xxx.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Xxx Xxx.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Xxx merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
